Feat/sessions
hngx-org/mentorme-be pull request #55
Opened 2023-10-20 18:09 UTC by Ifechukwu001

2023-10-25 21:51 UTC, zxenonx requested changes
Thanks @Ifechukwu001 
I left some comments

2023-10-25 21:51 UTC, zxenonx commented on mentoring/views.py
>                  return Response({"Message":"No resource containing '{}' found!".format(search_term)}, status=status.HTTP_404_NOT_FOUND)
Kindly use f-string instead here

2023-10-25 21:51 UTC, zxenonx commented on mentoring/views.py
> +        return None
You can remove this

2023-10-25 21:51 UTC, zxenonx commented on mentoring/views.py
> +        return None
You can remove this

2023-10-25 21:51 UTC, zxenonx commented on mentoring/urls.py
> +    path("sessions/mentee/canceled", views.SessMenteeCanceledRetrieveAPIView.as_view()),
What do these 2 endpoints do?

2023-10-26 23:06 UTC, Ifechukwu001 commented on mentoring/urls.py
> +    path("sessions/mentee/canceled", views.SessMenteeCanceledRetrieveAPIView.as_view()),
The one for booked, is for a mentee to book a session with the mentor

2023-10-26 23:08 UTC, Ifechukwu001 commented on mentoring/views.py
> +        return None
I put them there to avoid swagger from throwing errors when it loads.

2023-10-26 23:09 UTC, Ifechukwu001 commented on mentoring/views.py
> +        return None
Since the serializer is not needed in the view

2023-10-26 23:09 UTC, Ifechukwu001 commented on mentoring/views.py
> +        return None
I put them there to avoid swagger from throwing errors when it loads.
I will remove the whole view.
I couldn't implement this

2023-10-27 18:21 UTC, zxenonx commented on mentoring/views.py
> +        return None
Okay...

2023-10-27 18:21 UTC, zxenonx commented on mentoring/views.py
> +        return None
Okay

2023-10-27 18:23 UTC, zxenonx commented on mentoring/urls.py
> +    path("sessions/mentee/canceled", views.SessMenteeCanceledRetrieveAPIView.as_view()),
The API naming conventions have not been followed here.
I also checked the views file, we really need to refactor things there.
I'd need the brief of this project.
Thanks @Ifechukwu001

2023-10-27 18:26 UTC, zxenonx reviewed
Thanks @Ifechukwu001 
I left another comment

2023-10-27 18:26 UTC, zxenonx commented on mentoring/views.py
> +            return Response({"detail":"you no allowed to update this Resource"},status=status.HTTP_403_FORBIDDEN)
here, why not just "error" instead of detail.
That'd be better IMO

2026-08-05 13:10 UTC, closed without merging